### ISSUE TITLE
I can not install zapier-platform-cli on kubuntu 18.04

### ISSUE THREAD

**Issue by sallee113** [zapier/visual-builder#121]
There is npm debug log in the attachment
[npm-debug.log](https://github.com/zapier/visual-builder/files/4937045/npm-debug.log)

Could anybody help me?

**Comment by xavdid** [comment]
The bottom of your log says the following: 

```
26587 error typeerror Error: Missing required argument #1
26587 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
26587 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
26587 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
26587 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
26587 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
26587 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
26587 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
26587 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
26587 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
26587 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
26588 error typeerror This is an error with npm itself. Please report this error at:
26588 error typeerror     <http://github.com/npm/npm/issues>
```

So I'd report it to them.
