### ISSUE TITLE
https://platform.zapier.com/quickstart/auth

### ISSUE THREAD

**Issue by bogdan-around** [zapier/visual-builder#177]
**Link to documentation with issue**

Enter the URL of the page with the issue, e.g.: https://zapier.github.io/visual-builder/

**Describe the content issue**

https://platform.zapier.com/quickstart/auth

**What could be improved?**

I'm just following the tutorial and the authentication fails with this message
`
authentication failed: The app returned "Requires authentication". What happened (You are seeing this because you are an admin): Stack trace: ResponseError: {"status":401,"headers":{"content-type":"application/json; charset=utf-8"},"content":"{\"message\":\"Requires authentication\",\"documentation_url\":\"https://docs.github.com/rest/reference/users#get-the-authenticated-user\"}","request":{"url":"https://api.github.com/user"}} at Object.throwForStatus (/var/task/node_modules/zapier-platform-core/src/http-middlewares/after/throw-for-status.js:7:11) From previous event: at executeHttpRequest (/var/task/node_modules/zapier-platform-core/src/execute.js:22:6) at execute (/var/task/node_modules/zapier-platform-core/src/execute.js:90:12) at input (/var/task/node_modules/zapier-platform-core/src/create-command-handler.js:29:14) at Object.beforeMiddleware.then.newInput (/var/task/node_modules/zapier-platform-core/src/middleware.js:90:22) at bound (domain.js:402:14) at Object.runBound (domain.js:415:12) From previous event: at input (/var/task/node_modules/zapier-platform-core/src/middleware.js:89:45) at loadApp.then.appRaw (/var/task/node_modules/zapier-platform-core/src/tools/create-lambda-handler.js:215:18) at bound (domain.js:402:14) at runBound (domain.js:415:12) at runCallback (timers.js:705:18) at tryOnImmediate (timers.js:676:5) at processImmediate (timers.js:658:5) at process.topLevelDomainCallback (domain.js:126:23) From previous event: at Domain.handlerDomain.run (/var/task/node_modules/zapier-platform-core/src/tools/create-lambda-handler.js:200:10) at Domain.run (domain.js:349:14) at Runtime.handler (/var/task/node_modules/zapier-platform-core/src/tools/create-lambda-handler.js:192:19) at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)`

**Screenshots**

Add screenshots to help explain the issue, if needed.

**Additional context**

- authentication: Basic Auth
- API endpoint: `https://api.github.com/user`
- connection label: `{{bundle.authData.username}}`

**Comment by xavdid** [comment]
Can you post the code you've written? Or are you using the example code and that's what's not working?

**Comment by bogdan-around** [comment]
I'm using example code. No code created by me
https://platform.zapier.com/quickstart/auth

**Comment by xavdid** [comment]
@bogdan-around I just went through this tutorial and confirmed it's working normally for me.

One thing to note - if you've got 2FA enabled on your github account (and you should!), then your regular password won't work. You'll need to follow [these instructions](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) to use a personal access token instead of your password.
